import React, { useEffect } from "react";
import Container from "../components/layout/Container";
import { AlertTriangle, Briefcase, FileSignature, CheckSquare } from "lucide-react";

export default function Terms() {
  useEffect(() => {
    document.title = "Terms & Conditions | MasterCall";
    const metaDesc = document.querySelector('meta[name="description"]');
    if (metaDesc) {
      metaDesc.setAttribute("content", "Terms and Conditions for using the MasterCall enterprise call tracking software.");
    }
  }, []);

  return (
    <div className="pt-32 pb-24 bg-background min-h-screen">
      <Container>
        <div className="max-w-4xl mx-auto bg-white/5 border border-white/10 p-8 md:p-12 rounded-2xl shadow-xl">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-primary-500/10 text-primary-500 rounded-full text-xs font-bold border border-primary-500/20 mb-6 uppercase tracking-wider">
            <FileSignature size={14} />
            Legal Agreement
          </div>
          <h1 className="text-4xl md:text-5xl font-black text-white mb-6">Terms & Conditions</h1>
          <p className="text-neutral-400 text-lg mb-10 border-b border-white/10 pb-10">
            Last updated: {new Date().toLocaleDateString()}
          </p>

          <div className="space-y-12 text-neutral-300">
            <section>
              <h2 className="text-2xl font-bold text-white mb-4 flex items-center gap-3">
                <Briefcase className="text-primary-500" />
                1. Internal Enterprise Use Only
              </h2>
              <p className="mb-4 leading-relaxed">
                MasterCall is a proprietary application developed exclusively for internal use by authorized spa and salon branches within our organization. <strong>This application is NOT available to or intended for the general public.</strong>
              </p>
              <p className="leading-relaxed">
                Access to the platform requires a valid security token generated by our internal CRM system. Any attempt to bypass this authentication, distribute tokens, or reverse engineer the application is strictly prohibited and will result in immediate termination of access and potential disciplinary or legal action.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4 flex items-center gap-3">
                <CheckSquare className="text-primary-500" />
                2. Authorized Usage Restrictions
              </h2>
              <p className="mb-4 leading-relaxed">
                As an authorized user of MasterCall, you agree to the following restrictions:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>You will only install and use the application on company-approved devices.</li>
                <li>You will not use the application to intercept, log, or monitor personal calls unrelated to business operations.</li>
                <li>You will maintain the confidentiality of your access tokens and internal CRM credentials.</li>
                <li>You will promptly report any lost or stolen devices that have the MasterCall app installed.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4 flex items-center gap-3">
                <AlertTriangle className="text-yellow-500" />
                3. No Misuse Policy
              </h2>
              <p className="mb-4 leading-relaxed">
                The data collected by MasterCall (including call logs and phone numbers) contains sensitive business information and customer leads. Misuse of this data, including but not limited to unauthorized downloading, sharing with competitors, or utilizing leads for personal gain, is a direct violation of company policy.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">
                4. Liability Disclaimer
              </h2>
              <p className="mb-4 leading-relaxed">
                MasterCall is provided "as is" for internal operational purposes. While we strive for 100% uptime and accurate data synchronization, the organization assumes no liability for technical failures, missed logs due to connectivity issues, or device malfunctions.
              </p>
              <p className="leading-relaxed">
                Users must ensure devices are connected to the internet periodically to allow for proper data synchronization to the CRM.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">
                5. Contact & Support
              </h2>
              <p className="mb-4 leading-relaxed">
                For technical support or to report a violation of these terms, please contact:
              </p>
              <a href="mailto:email-us@dishaonlinesolution.in" className="text-primary-400 hover:text-primary-300 font-medium">
                email-us@dishaonlinesolution.in
              </a>
            </section>
          </div>
        </div>
      </Container>
    </div>
  );
}
